spring.application.name=openc2-consumer

##Configuración de evidencias
# LISTA DE EVIDENCIAS DISPONIBLES PARA SER PROCESADAS POR EL CONSUMIDOR DE OPENC2
# Para añadir una nueva, solo escribe su sufijo al final de la lista (sin espacios) y añade el artefacto
# al directorio artifacts.path
ueba.evidences=userlogon,usersession,userlogout,usersessionduration
#ruta a los ficheros de artefactos (cada artefacto es un fichero con el mismo nombre que el nombre de la evidencia)
artifacts.path=D:\\soardata\\artifacts

velociraptor.host=localhost
velociraptor.port=8000
velociraptor.ssl=false
velociraptor.username=admin
velociraptor.password=admin